# Generated by Django 6.0.1 on 2026-01-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt_coderr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(
                blank=True, null=True, upload_to='profiles/'),
        ),
    ]
