# Generated by Django 6.0.1 on 2026-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markt_coderr', '0002_alter_offer_image_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
